### ISSUE TITLE
Packaging nodert in electron

### ISSUE THREAD

**Issue by ShafSpecs** [xan105/node-nodeRT#5]
Hello :wave:, how is nodert packaged with electron? Everytime I package it normally and build it, then attempt to run the installed, native app, I get an error about missing imports. Using it in dev and preview works, but packaging it seems to break the package

**Comment by ShafSpecs** [comment]
I am importing it normally btw:
```ts
import { devices } from '@xan105/nodert'
```

**Comment by ShafSpecs** [comment]
The error:
![image](https://github.com/xan105/node-nodeRT/assets/69679506/eb7bc264-ad10-4023-b13c-364e1a18cf08)

**Comment by xan105** [comment]
It's pretty late so I can't check right now. But I just noticed that the actual filename has an uppercase char in its name 
`applicationmodel.js` -> `applicationModel.js` (nb: auto generated files; didn't notice)
Maybe it does not work because asar is case sensitive ?

**Comment by xan105** [comment]
Ok so somehow `applicationmodel.js` had an uppercase char in its name **on GitHub** but not on my filesystem 🤔 and I didn't notice until now.
Since I now use Github action to publish the package to npm, _"that mistake"_ got push to the npm package as well.

I've updated the package (2.1.2 | [5572a3c](https://github.com/xan105/node-nodeRT/commit/5572a3c9cc871a929e684c423b1494cf3b01226a)); I believe this should fix your error. Let me know.

Sorry for the inconvenience.

**Comment by ShafSpecs** [comment]
> Ok so somehow `applicationmodel.js` had an uppercase char in its name **on GitHub** but not on my filesystem 🤔 and I didn't notice until now. Since I now use Github action to publish the package to npm, _"that mistake"_ got push to the npm package as well.
> 
> I've updated the package (2.1.2 | [5572a3c](https://github.com/xan105/node-nodeRT/commit/5572a3c9cc871a929e684c423b1494cf3b01226a)); I believe this should fix your error. Let me know.
> 
> Sorry for the inconvenience.

Thanks. It no longer throws errors, still opens as expected. But for some reason, doesn't work. I think that's a me thing though, would debug and get back to you :)

**Comment by ShafSpecs** [comment]
> I've updated the package (2.1.2 | [5572a3c](https://github.com/xan105/node-nodeRT/commit/5572a3c9cc871a929e684c423b1494cf3b01226a)); I believe this should fix your error. Let me know.

Still doesn't work when packaged.

I get this error now:
```
(node:17656) UnhandledPromiseRejectionWarning: TypeError: devices.geolocation.Geolocator is not a constructor
    at subscribeToGeolocation (file:///C:/Users/user/AppData/Local/Programs/project/resources/app.asar/out/main/index.js:15336:23)
    at file:///C:/Users/user/AppData/Local/Programs/project/resources/app.asar/out/main/index.js:15698:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:17656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```
I am importing `devices` normally:
```js
import { devices } from '@xan105/nodert'
```
And instantiating geolocation normally:
```js
const geolocation = new devices.geolocation.Geolocator()
```

**Comment by ShafSpecs** [comment]
Geolocator seems to be undefined in the packaged build. Maybe a `*.node` thing? Would debug

**Comment by xan105** [comment]
I do not know which build process / system you are using to _package_ your Electron app; 
but when using asar archive you need to leave native modules unpacked using the `--unpack` option.
eg: `npx asar pack "/path/to/source" "/path/to/dest" --unpack *.node`
cf: https://www.electronjs.org/docs/latest/tutorial/asar-archives#limitations-of-the-node-api

Native modules should thus end up in `./resources/app.asar.unpacked` directory next to `app.asar`.
Hence this line in my `.node` file loader 
https://github.com/xan105/node-nodeRT/blob/5572a3c9cc871a929e684c423b1494cf3b01226a/lib/util/load.js#L35

**Comment by ShafSpecs** [comment]
Fixed it. Thanks ❤️
